# GitHub Dependabot para mantener prebuilds actualizados
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/combustibles"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "npm"
    directory: "/alimentacion"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"