-- ===========================================
-- CREACIÓN DE TABLAS - Forestech Combustibles
-- Azure SQL Server
-- ===========================================

USE forestechCombus;
GO

-- 1. MOVIMIENTOS DE COMBUSTIBLE
CREATE TABLE combustibles_movements (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    type NVARCHAR(50) NOT NULL,
    fuelType NVARCHAR(100) NOT NULL,
    quantity DECIMAL(18,3) NOT NULL,
    unitPrice DECIMAL(18,2) DEFAULT 0,
    totalValue DECIMAL(18,2) NOT NULL,
    vehicleId NVARCHAR(100),
    location NVARCHAR(200),
    destinationLocation NVARCHAR(200),
    description NVARCHAR(MAX),
    effectiveDate DATETIME2,
    hourMeterReading DECIMAL(10,2),
    hoursWorked DECIMAL(8,2) DEFAULT 0,
    previousHourMeterReading DECIMAL(10,2),
    createdBy NVARCHAR(200),
    createdByUid NVARCHAR(100),
    createdByName NVARCHAR(200),
    status NVARCHAR(50) DEFAULT 'completed',
    approvedBy NVARCHAR(200),
    approvedAt DATETIME2,
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    INDEX idx_type (type),
    INDEX idx_fuel_type (fuelType),
    INDEX idx_vehicle (vehicleId),
    INDEX idx_location (location),
    INDEX idx_created_at (createdAt),
    INDEX idx_effective_date (effectiveDate)
);

-- 2. INVENTARIO
CREATE TABLE combustibles_inventory (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    fuelType NVARCHAR(100) NOT NULL,
    name NVARCHAR(200) NOT NULL,
    description NVARCHAR(MAX),
    currentStock DECIMAL(18,3) NOT NULL DEFAULT 0,
    maxCapacity DECIMAL(18,3) NOT NULL,
    minThreshold DECIMAL(18,3) DEFAULT 0,
    unit NVARCHAR(50) DEFAULT 'galones',
    location NVARCHAR(200) NOT NULL,
    pricePerUnit DECIMAL(18,2) DEFAULT 0,
    supplier NVARCHAR(200),
    status NVARCHAR(50) DEFAULT 'active',
    lastMovementId UNIQUEIDENTIFIER,
    lastMovementType NVARCHAR(50),
    lastMovementQuantity DECIMAL(18,3),
    lastMovementDate DATETIME2,
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    updatedBy NVARCHAR(100),
    CONSTRAINT chk_stock_positive CHECK (currentStock >= 0),
    CONSTRAINT chk_capacity_positive CHECK (maxCapacity > 0),
    CONSTRAINT chk_min_threshold CHECK (minThreshold >= 0),
    UNIQUE KEY uk_fuel_location (fuelType, location),
    INDEX idx_fuel_type (fuelType),
    INDEX idx_location (location),
    INDEX idx_status (status),
    INDEX idx_updated_at (updatedAt)
);

-- 3. VEHÍCULOS
CREATE TABLE combustibles_vehicles (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    vehicleId NVARCHAR(100) NOT NULL UNIQUE,
    name NVARCHAR(200) NOT NULL,
    brand NVARCHAR(100),
    model NVARCHAR(100),
    type NVARCHAR(100) NOT NULL,
    category NVARCHAR(100),
    enginePower DECIMAL(10,2),
    fuelCapacity DECIMAL(10,2),
    fuelType NVARCHAR(50) NOT NULL,
    currentLocation NVARCHAR(200),
    operationalStatus NVARCHAR(50) DEFAULT 'activo',
    priority NVARCHAR(50) DEFAULT 'media',
    hasHourMeter BIT DEFAULT 0,
    initialHourMeter DECIMAL(10,2),
    currentHourMeter DECIMAL(10,2),
    totalHoursWorked DECIMAL(10,2) DEFAULT 0,
    lastHourMeterUpdate DATETIME2,
    fuelConsumptionPerHour DECIMAL(8,3),
    hourMeterHistory NVARCHAR(MAX),
    totalFuelConsumed DECIMAL(18,3) DEFAULT 0,
    totalMovements INT DEFAULT 0,
    lastMovementDate DATETIME2,
    estimatedConsumptionPerHour DECIMAL(8,3),
    actualConsumptionPerHour DECIMAL(8,3),
    maintenanceHistory NVARCHAR(MAX),
    lastMaintenanceDate DATETIME2,
    notes NVARCHAR(MAX),
    searchTags NVARCHAR(MAX),
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    updatedBy NVARCHAR(100),
    INDEX idx_vehicle_id (vehicleId),
    INDEX idx_type (type),
    INDEX idx_category (category),
    INDEX idx_fuel_type (fuelType),
    INDEX idx_status (operationalStatus),
    INDEX idx_location (currentLocation),
    INDEX idx_updated_at (updatedAt)
);

-- 4. MANTENIMIENTO
CREATE TABLE combustibles_maintenance (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    movementId UNIQUEIDENTIFIER,
    vehicleId NVARCHAR(100),
    vehicleName NVARCHAR(200),
    type NVARCHAR(50) DEFAULT 'preventivo',
    priority NVARCHAR(50) DEFAULT 'media',
    title NVARCHAR(200) NOT NULL,
    description NVARCHAR(MAX),
    notes NVARCHAR(MAX),
    hours DECIMAL(8,2) DEFAULT 0,
    laborCost DECIMAL(18,2) DEFAULT 0,
    technician NVARCHAR(200),
    parts NVARCHAR(MAX),
    totalPartsCost DECIMAL(18,2) DEFAULT 0,
    fuelType NVARCHAR(50),
    fuelQuantity DECIMAL(18,3),
    fuelCost DECIMAL(18,2),
    scheduledDate DATETIME2,
    completedDate DATETIME2,
    status NVARCHAR(50) DEFAULT 'completado',
    totalCost DECIMAL(18,2),
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    INDEX idx_vehicle (vehicleId),
    INDEX idx_movement (movementId),
    INDEX idx_type (type),
    INDEX idx_status (status),
    INDEX idx_scheduled_date (scheduledDate),
    INDEX idx_completed_date (completedDate)
);

-- 5. PRODUCTOS
CREATE TABLE combustibles_products (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    code NVARCHAR(100) UNIQUE,
    name NVARCHAR(200) NOT NULL,
    displayName NVARCHAR(200),
    description NVARCHAR(MAX),
    category NVARCHAR(100) DEFAULT 'combustible',
    subcategory NVARCHAR(100),
    type NVARCHAR(100),
    unit NVARCHAR(50) DEFAULT 'galones',
    density DECIMAL(8,4),
    energyContent DECIMAL(10,2),
    currentStock DECIMAL(18,3) DEFAULT 0,
    minThreshold DECIMAL(18,3) DEFAULT 0,
    maxStock DECIMAL(18,3),
    basePrice DECIMAL(18,2),
    currentPrice DECIMAL(18,2),
    costPrice DECIMAL(18,2),
    isActive BIT DEFAULT 1,
    status NVARCHAR(50) DEFAULT 'active',
    suppliers NVARCHAR(MAX),
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    updatedBy NVARCHAR(100),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_category (category),
    INDEX idx_is_active (isActive),
    INDEX idx_status (status)
);

-- 6. PROVEEDORES
CREATE TABLE combustibles_suppliers (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name NVARCHAR(200) NOT NULL UNIQUE,
    taxId NVARCHAR(100) UNIQUE,
    type NVARCHAR(50) DEFAULT 'proveedor',
    category NVARCHAR(50) DEFAULT 'combustibles',
    contactPerson NVARCHAR(200),
    phone NVARCHAR(50),
    email NVARCHAR(200),
    address NVARCHAR(MAX),
    city NVARCHAR(100),
    state NVARCHAR(100) DEFAULT 'Colombia',
    fuelTypes NVARCHAR(MAX),
    paymentTerms NVARCHAR(50) DEFAULT 'contado',
    creditLimit DECIMAL(18,2) DEFAULT 0,
    priceList NVARCHAR(MAX),
    rating DECIMAL(3,1) DEFAULT 5.0,
    evaluationNotes NVARCHAR(MAX),
    status NVARCHAR(50) DEFAULT 'active',
    isPreferred BIT DEFAULT 0,
    totalOrders INT DEFAULT 0,
    totalPurchased DECIMAL(18,2) DEFAULT 0,
    lastOrderDate DATETIME2,
    averageDeliveryTime DECIMAL(8,2),
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    updatedBy NVARCHAR(100),
    INDEX idx_name (name),
    INDEX idx_tax_id (taxId),
    INDEX idx_type (type),
    INDEX idx_status (status),
    INDEX idx_is_preferred (isPreferred),
    INDEX idx_rating (rating)
);

-- 7. CATEGORÍAS DE VEHÍCULOS
CREATE TABLE combustibles_vehicle_categories (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name NVARCHAR(200) NOT NULL UNIQUE,
    code NVARCHAR(50) UNIQUE,
    description NVARCHAR(MAX),
    type NVARCHAR(50) DEFAULT 'vehicle',
    icon NVARCHAR(100),
    color NVARCHAR(50),
    customFields NVARCHAR(MAX),
    defaultFuelType NVARCHAR(50),
    estimatedConsumption DECIMAL(8,3),
    isActive BIT DEFAULT 1,
    sortOrder INT DEFAULT 0,
    vehicleCount INT DEFAULT 0,
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    updatedBy NVARCHAR(100),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_type (type),
    INDEX idx_is_active (isActive),
    INDEX idx_sort_order (sortOrder)
);

-- 8. CATEGORÍAS DE PRODUCTOS
CREATE TABLE product_categories (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name NVARCHAR(200) NOT NULL UNIQUE,
    code NVARCHAR(50) UNIQUE,
    description NVARCHAR(MAX),
    parentId UNIQUEIDENTIFIER,
    level INT DEFAULT 1,
    path NVARCHAR(500),
    icon NVARCHAR(100),
    color NVARCHAR(50),
    sortOrder INT DEFAULT 0,
    isActive BIT DEFAULT 1,
    productCount INT DEFAULT 0,
    createdAt DATETIME2 DEFAULT GETUTCDATE(),
    updatedAt DATETIME2 DEFAULT GETUTCDATE(),
    createdBy NVARCHAR(100),
    updatedBy NVARCHAR(100),
    FOREIGN KEY (parentId) REFERENCES product_categories(id),
    INDEX idx_code (code),
    INDEX idx_name (name),
    INDEX idx_parent (parentId),
    INDEX idx_level (level),
    INDEX idx_is_active (isActive),
    INDEX idx_sort_order (sortOrder)
);

PRINT '✅ Todas las tablas creadas exitosamente';
PRINT 'Base de datos forestechCombus lista para usar';
GO
