name: ❓ Pregunta - Copilot Explica
description: "¿Tienes una duda sobre el código o cómo funciona algo? ¡Pregúntale a Copilot!"
title: "[❓ CONSULTA] "
labels: ["copilot-agent", "question"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤔 ¡Excelente! Tienes una pregunta
        
        **Copilot puede ayudarte con:**
        
        📚 **Explicar** cómo funciona el código  
        🔍 **Encontrar** donde está implementada una función  
        🧭 **Guiarte** para implementar algo tú mismo  
        🏗️ **Recomendar** la mejor arquitectura o patrón  
        🐛 **Investigar** por qué algo no funciona como esperas

        ---

  - type: dropdown
    id: tipo_consulta
    attributes:
      label: "🎯 ¿Qué tipo de ayuda necesitas?"
      description: "Esto ayuda a Copilot a darte la mejor respuesta"
      options:
        - "📚 Explicar - ¿Cómo funciona este código?"
        - "🔍 Encontrar - ¿Dónde está implementado X?"
        - "🧭 Guiar - ¿Cómo implemento Y?"
        - "🏗️ Arquitectura - ¿Cuál es la mejor forma de Z?"
        - "🐛 Investigar - ¿Por qué pasa esto?"
        - "📖 Documentar - ¿Puedes explicar esto para el equipo?"
        - "🤔 Otra cosa"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: "📍 ¿Sobre qué área de Forestech?"
      description: "Para que Copilot sepa dónde buscar"
      options:
        - "🍽️ Alimentación (liquidaciones de comidas)"
        - "⛽ Combustibles (inventario y vehículos)"
        - "🔧 Shared (componentes reutilizables)"
        - "🔥 Firebase (base de datos, auth, storage)"
        - "🎨 Frontend (React, componentes, hooks)"
        - "🏗️ Build/Deploy (configuración, CI/CD)"
        - "📱 Mobile/Responsive (diseño móvil)"
        - "🧪 Testing (pruebas y validación)"
        - "🔐 Seguridad (permisos, validaciones)"
        - "🌐 General (arquitectura del proyecto)"
    validations:
      required: true

  - type: textarea
    id: pregunta
    attributes:
      label: "❓ ¿Cuál es tu pregunta?"
      description: "Explica tu duda con el mayor detalle posible"
      placeholder: |
        Ejemplos de buenas preguntas:
        
        📚 Explicar:
        "¿Cómo funciona el sistema de roles en Firebase? Veo admin, operator y viewer pero no entiendo cómo se validan"
        
        🔍 Encontrar:
        "¿En qué archivo está la función que calcula el precio total de combustible? Necesito modificarla"
        
        🧭 Guiar:
        "Quiero agregar una notificación push cuando el stock está bajo. ¿Por dónde empiezo?"
        
        🏗️ Arquitectura:
        "¿Debería crear un nuevo componente o modificar uno existente para mostrar gráficos de consumo?"
        
        💡 Tip: Mientras más contexto des, mejor respuesta recibirás
    validations:
      required: true

  - type: textarea
    id: contexto
    attributes:
      label: "📝 OPCIONAL: ¿Contexto adicional?"
      description: "Información extra que puede ayudar"
      placeholder: |
        Ejemplos:
        - "Esto es para el reporte mensual que envío a gerencia"
        - "Estoy siguiendo el patrón de la página de vehículos"
        - "El error aparece solo en producción, en desarrollo funciona"
        - "Soy nuevo en React/Firebase"
        - "Ya revisé el archivo X pero no entiendo Y"

  - type: dropdown
    id: nivel_tecnico
    attributes:
      label: "🎓 ¿Cuál es tu nivel técnico?"
      description: "Para que Copilot adapte la explicación"
      options:
        - "🆕 Principiante - Soy nuevo en programación"
        - "📚 Intermedio - Sé programar pero soy nuevo en React/Firebase"
        - "🛠️ Avanzado - Conozco bien las tecnologías"
        - "🧙‍♂️ Experto - Solo necesito detalles específicos"
      default: 1
    validations:
      required: true

  - type: dropdown
    id: tipo_respuesta
    attributes:
      label: "💬 ¿Qué tipo de respuesta prefieres?"
      description: "Copilot adaptará su estilo"
      options:
        - "📖 Explicación detallada con ejemplos"
        - "📝 Paso a paso (tutorial)"
        - "💡 Respuesta rápida y directa"
        - "🔗 Referencias a código existente"
        - "📚 Documentación para compartir con el equipo"
      default: 0

  - type: checkboxes
    id: confirmacion
    attributes:
      label: "✅ Confirmación final"
      description: "Marca para enviar a Copilot"
      options:
        - label: "He explicado claramente mi pregunta"
          required: true
        - label: "He dado suficiente contexto para una buena respuesta"
          required: true
        - label: "Entiendo que @github-copilot responderá en este issue"
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🤖 ¿Qué pasa después?
        
        **Copilot va a:**
        
        1. **Analizar** tu pregunta y el contexto
        2. **Investigar** el código relevante de Forestech
        3. **Preparar** una respuesta adaptada a tu nivel
        4. **Incluir** ejemplos prácticos y referencias
        5. **Responder** directamente en este issue
        
        **🎯 Tipos de respuesta según tu consulta:**
        
        - **📚 Explicaciones**: Incluirán diagramas y ejemplos del código real
        - **🔍 Ubicaciones**: Te mostrarán exactamente dónde está cada cosa
        - **🧭 Guías**: Te darán pasos específicos adaptados a Forestech
        - **🏗️ Arquitectura**: Te recomendarán patrones ya usados en el proyecto
        - **🐛 Investigaciones**: Analizarán logs, código y configuración
        
        ⏱️ **Tiempo de respuesta**: Generalmente 5-15 minutos
        
        **💡 Tip extra:** Copilot puede crear ejemplos de código funcional específicos para tu caso, no solo explicaciones genéricas.
        
        🎉 **¡Tu duda será resuelta con contexto específico de Forestech!**