name:  Reporte de Error
description: Reporta un error o problema con el sistema
title: "[ERROR] "
labels: ["error"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un error. Por favor llena la informaci贸n a continuaci贸n.
        
  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n del Error
      description: Describe qu茅 error est谩s experimentando
      placeholder: Explica qu茅 sucedi贸 y qu茅 esperabas que sucediera
    validations:
      required: true
      
  - type: dropdown
    id: aplicacion
    attributes:
      label: Aplicaci贸n Afectada
      description: 驴En qu茅 aplicaci贸n ocurre el error?
      options:
        - alimentacion (App de alimentaci贸n bovina)
        - combustibles (App de gesti贸n de combustibles)
        - shared (Componentes compartidos)
        - build/ci (Sistema de construcci贸n)
        - documentacion
    validations:
      required: true
      
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para Reproducir
      description: Lista los pasos para reproducir el error
      placeholder: |
        1. Navega a...
        2. Haz clic en...
        3. El error aparece...
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Logs de Error
      description: Copia cualquier mensaje de error de la consola
      render: shell
